### PR TITLE
Remove old manual menu page

### PR DESCRIPTION
**Pull request by mrhut10**
I poorely named the commits, however this deletes the old manual menu page and creates it programmatically as with the others.

### CODE REVIEW

**Comment by mrhut10** [comment]
@lukebennett88 this pr removes the old menu page and defines it the same as the rest of them programically.

**Comment by lukebennett88** [comment]
I couldn't get this to merge (I suck at git) so I've manually added all the changes into master and will close this PR.

Thanks so much @mrhut10 you were a huge help, I definitely wouldn't have been able to do this by myself.

**Comment by mrhut10** [comment]
Everyone sucks at git man, lol. It's just some black magic.

I actually learnt a few things in working on your stuff with git last night too.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mrhut10** [comment]
Maybe in the future we can do videos or podcast about these technologies and living in a regional area.

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request closed without merging**
